# This file was generated by GoReleaser. DO NOT EDIT.
cask "exegol" do
  name "exegol"
  desc "Private container workspace manager"
  homepage "https://github.com/anhhung04/Exegol"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "exegol"

  on_macos do
    on_intel do
      url "https://github.com/anhhung04/Exegol/releases/download/v#{version}/exegol_#{version}_darwin_amd64.tar.gz"
      sha256 "f5c2f2a235110d6f8c0d5fd810e65c8975a74592b39897e63d9797a26d8a2fd3"
    end
    on_arm do
      url "https://github.com/anhhung04/Exegol/releases/download/v#{version}/exegol_#{version}_darwin_arm64.tar.gz"
      sha256 "79295b62c71d10cb8438a061c612adaaad2344513a38b30645d425771cebeff7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anhhung04/Exegol/releases/download/v#{version}/exegol_#{version}_linux_amd64.tar.gz"
      sha256 "e11205d41aef8e7e82a70a130e60c3755203c4778954edb03c8f2fd095895a76"
    end
    on_arm do
      url "https://github.com/anhhung04/Exegol/releases/download/v#{version}/exegol_#{version}_linux_arm64.tar.gz"
      sha256 "131150dc1b523b135d4af826fa918a892e9a33533a77db4f3bb1b1d3a0b2d2f8"
    end
  end

  # No zap stanza required
end
